// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: domain_checker.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DomainChecker_CheckDomains_FullMethodName = "/checker.DomainChecker/CheckDomains"
)

// DomainCheckerClient is the client API for DomainChecker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DomainCheckerClient interface {
	CheckDomains(ctx context.Context, in *DomainRequest, opts ...grpc.CallOption) (*DomainResponse, error)
}

type domainCheckerClient struct {
	cc grpc.ClientConnInterface
}

func NewDomainCheckerClient(cc grpc.ClientConnInterface) DomainCheckerClient {
	return &domainCheckerClient{cc}
}

func (c *domainCheckerClient) CheckDomains(ctx context.Context, in *DomainRequest, opts ...grpc.CallOption) (*DomainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DomainResponse)
	err := c.cc.Invoke(ctx, DomainChecker_CheckDomains_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DomainCheckerServer is the server API for DomainChecker service.
// All implementations must embed UnimplementedDomainCheckerServer
// for forward compatibility.
type DomainCheckerServer interface {
	CheckDomains(context.Context, *DomainRequest) (*DomainResponse, error)
	mustEmbedUnimplementedDomainCheckerServer()
}

// UnimplementedDomainCheckerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDomainCheckerServer struct{}

func (UnimplementedDomainCheckerServer) CheckDomains(context.Context, *DomainRequest) (*DomainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckDomains not implemented")
}
func (UnimplementedDomainCheckerServer) mustEmbedUnimplementedDomainCheckerServer() {}
func (UnimplementedDomainCheckerServer) testEmbeddedByValue()                       {}

// UnsafeDomainCheckerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DomainCheckerServer will
// result in compilation errors.
type UnsafeDomainCheckerServer interface {
	mustEmbedUnimplementedDomainCheckerServer()
}

func RegisterDomainCheckerServer(s grpc.ServiceRegistrar, srv DomainCheckerServer) {
	// If the following call pancis, it indicates UnimplementedDomainCheckerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DomainChecker_ServiceDesc, srv)
}

func _DomainChecker_CheckDomains_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DomainCheckerServer).CheckDomains(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DomainChecker_CheckDomains_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DomainCheckerServer).CheckDomains(ctx, req.(*DomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DomainChecker_ServiceDesc is the grpc.ServiceDesc for DomainChecker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DomainChecker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "checker.DomainChecker",
	HandlerType: (*DomainCheckerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckDomains",
			Handler:    _DomainChecker_CheckDomains_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "domain_checker.proto",
}
